{{ if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: {{ .Values.backup.image }}
            args:
            - /bin/sh
            - -c
            - "echo FIXME!"
            restartPolicy: onFailure
{{ end }}