{{ if and .Values.db.enabled .Values.db.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - name: postgres
    port: {{ .Values.db.service.port }}
{{ end }}

