{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyway
spec:
  selector:
    matchLabels:
      app: anyway
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anyway
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: anyway
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources: {{ .Values.resources }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          {{ if .Values.restore.enabled }}
          initialDelaySeconds: 180
          {{ else }}
          initialDelaySeconds: 60
          {{ end }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          {{ if .Values.restore.enabled }}
          initialDelaySeconds: 180
          {{ else }}
          initialDelaySeconds: 60
          {{ end }}
        envFrom:
        - secretRef: {"name": "anyway"}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: {"secretKeyRef":{"name":"db", "key":"POSTGRES_PASSWORD"}}
        - name: DATABASE_URL
          value: "postgresql://anyway:$(POSTGRES_PASSWORD)@db/anyway"
        - name: GUNICORN_CMD_ARGS
          value: "--bind=0.0.0.0"
{{ end }}
