{{ if and .Values.enabled .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: anyway
spec:
  selector:
    app: anyway
  ports:
  - name: http
    port: {{ .Values.service.port }}
{{ end }}
